### ISSUE TITLE
ошибки в "install-theme.sh" и разделе "Instalation"

### ISSUE THREAD

**Issue by itz-me-zappex** [Andrey0189/recordrofi#1]
содержимое скрипта "install-theme.sh":
```
#!/bin/sh

mkdir ~/.config/rofi
cp .config/rofi/* $HOME/.config/rofi/*
```
во избежание ошибок в консоли и корректного выполнения должно быть исправлено на:
```
#!/bin/sh

mkdir ~/.config/rofi
cp -r .config/rofi/* ~/.config/rofi
```
(можно указать $HOME в обоих командах, особой роли не играет)

в названии раздела "Instalation" допущена ошибка, верно "Installation"

содержимое раздела "Installation" можно отредактировать до вот такого состояния:
```
$ git clone https://github.com/Andrey0189/recordrofi
$ cd recordrofi
$ chmod +x install-theme.sh recordrofi
$ ./install-theme.sh
$ sudo mv recordrofi /usr/bin
```
желаю удачи!

**Comment by Andrey0189** [comment]
Спасибо, исправлено

**Comment by Andrey0189** [comment]
Спасибо, исправлено
